In [1]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/hakimyameen/ML_Datasets/refs/heads/main/income_evaluation%20(1).csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [2]:
df.shape

(32561, 15)

In [3]:
df.columns

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' income'],
      dtype='object')

In [34]:
df.columns=df.columns.str.replace("_","-")
df.columns

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' income'],
      dtype='object')

In [ ]:
# data encodeing
df["encoded_marital_statur"]=df[" marital_status"].apply(lambda x: 0 if x=="Never-married" else 1)
df["encoded_marital_statur"]
df.head(10)
df.drop(columns="encoded_marital_statur",inplace=True)
df["marital_status"].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [45]:
# list(df.groupby(' marital_status'))
#df.columns

#group rows by marital status and education
# list(df.groupby([" eduction, workclass"]))
df["workclass"].unique

<bound method Series.unique of 0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
               ...
32556              Private
32557              Private
32558              Private
32559              Private
32560         Self-emp-inc
Name: workclass, Length: 32561, dtype: object>

In [ ]:
list(df.groupby([' workclass']))
df.columns=df.columns.str.replace(" ","")

In [ ]:
#get the workclsses where it is self-emp
#df["workclass"]=df["workclass"].apply(lambda x: x.replace(" ",""))
df.groupby("workclass").get_group("Self-emp-not-inc")
#df["workclass"]=df["workclass"].apply(lambda x: x.replace(" ",""))

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
39,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32456,30,Self-emp-not-inc,261943,11th,7,Married-spouse-absent,Craft-repair,Not-in-family,White,Male,0,0,30,Honduras,<=50K
32468,39,Self-emp-not-inc,193689,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,65,United-States,<=50K
32492,42,Self-emp-not-inc,217597,HS-grad,9,Divorced,Sales,Own-child,White,Male,0,0,50,?,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K

In [43]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [72]:
# find what is the average divorce rate where workclass is Private
df["marital-status"].apply
df.groupby(["workclass","marital-status"]).get_group(("Private","Divorced")).mean(numeric_only=True)

KeyError: ('Private', 'Divorced')

In [76]:
cnt=0
for i in df["marital-status"]:
    if i =="Divorced":
        cnt+=1
cnt

0

In [79]:
cnt = (df["marital-status"] == " Divorced").sum()
print(cnt)

4443

In [78]:
print(df["marital-status"].unique())

[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']

In [ ]:
# average divorce rate in private workclass
x=df.query("`marital-status`==' Divorced' and workclass=='Private'").shape[0]#or
x=len(df.query("`marital-status`==' Divorced' and workclass=='Private'"))#by len
x
# Count all people in the Private workclass
y = len(df.query("workclass == 'Private'"))
y
print("the average divorce rate in Private workclass is",x/y)

the average divorce rate in Private workclass is 0.13742509693338034

In [116]:
# get the unique education and education-num pairs
df[["education-num","education"]]
df[["education-num", "education"]].drop_duplicates().sort_values("education-num")

#df["education"].unique()
# tuple(df.groupby(["education","education-num"]))

     education-num      education
224              1      Preschool
160              2        1st-4th
56               3        5th-6th
15               4        7th-8th
6                5            9th
77               6           10th
3                7           11th
415              8           12th
2                9        HS-grad
10              10   Some-college
14              11      Assoc-voc
13              12     Assoc-acdm
0               13      Bachelors
5               14        Masters
52              15    Prof-school
20              16      Doctorate

In [117]:
#
df["native-country"].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [119]:
#
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
income            object
dtype: object

In [ ]:
# find average hours per week for each work class
list(df.groupby(["workclass","hours-per-week"]))
# df.groupby(["workclass","hours-per-week"]).mean()
df.groupby("workclass")["hours-per-week"].mean()# when we want to group by two cols and apply agg to one of them
# give second column in [].apply the agg function

workclass
?                   31.919390
Federal-gov         41.379167
Local-gov           40.982800
Never-worked        28.428571
Private             40.267096
Self-emp-inc        48.818100
Self-emp-not-inc    44.421881
State-gov           39.031587
Without-pay         32.714286
Name: hours-per-week, dtype: float64

In [129]:
#find the no of employees and aveg working hours
df.groupby("workclass")["hours-per-week"].agg(["mean", "count"])
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [136]:
df.groupby("education")["capital-gain"].sum()
df.groupby("education")["capital-gain"].agg(["sum","mean"])

                  sum          mean
education
10th           377468    404.574491
11th           252740    215.097872
12th           123010    284.087760
1st-4th         21147    125.875000
5th-6th         58615    176.021021
7th-8th        151125    233.939628
9th            175834    342.089494
Assoc-acdm     683306    640.399250
Assoc-voc      988201    715.051375
Bachelors     9404984   1756.299533
Doctorate     1970070   4770.145278
HS-grad       6056978    576.800114
Masters       4415297   2562.563552
Preschool       45818    898.392157
Prof-school   5998704  10414.416667
Some-college  4366027    598.824167

AttributeError: 'Series' object has no attribute 'category'

: